services:
  - type: web
    name: reservation-miniapp
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd miniapp-frontend && npm install && npm run build && mkdir -p ../static && cp -r build/* ../static/
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11